# Author socials
twitter: "https://twitter.com/afrid1808"
github: "https://github.com/afrid18"
email: "afridhussain.d@gmail.com"
name: "Afrid Hussain"
location: "Andhra Pradesh, India"
phone: "+917032376276"


