baseURL: 'https://afridhussain.tech' # Baseurl
languageCode: en-us
DefaultContentLanguage: en

title: Afrid Hussain

# Specifing theme as go modules
theme: github.com/lxndrblz/anatole

summarylength: 10

#Enabling emojis
enableEmoji: true

# No Idea what it is
enableRobotsTXT: true
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
localizedDates: false

taxonomies:
  category: categories
  series: series
  tag: tags
related:
  includeNewer: true
  threshold: 80
  toLower: true
  indices:
    - name: keywords
      weight: 100
    - name: tags
      weight: 80

# Module settings (Go modules and hugo modules)
module:
  imports:
    - path: github.com/lxndrblz/anatole
      disable: false

