baseURL: 'https://afridhussain.tech'
languageCode: en-us
DefaultContentLanguage: en

title: Afrid Hussain
author:
  twitter: "https://twitter.com/afrid1808"
  github: "https://github.com/afrid18"
  email: "afridhussain.d@gmail.com"
  name: "Afrid Hussain"
  location: "Andhra Pradesh, India"
  phone: "+917032376276"

theme: github.com/lxndrblz/anatole
summarylength: 10
enableEmoji: true
enableRobotsTXT: true
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
localizedDates: false
markup:
  goldmark:
    renderer:
      unsafe: true
taxonomies:
  category: categories
  series: series
  tag: tags
related:
  includeNewer: true
  threshold: 80
  toLower: true
  indices:
    - name: keywords
      weight: 100
    - name: tags
      weight: 80

module:
  imports:
    - path: github.com/lxndrblz/anatole
      disable: false

