title: I'm Afrid Hussain
author: Afrid Hussain
profilePicture: images/solana.jpeg
keywords: 'blog, portfolio'
description: |
  Open Source enthusiast
  Currently Blogging about GSoC'23
favicon: favicons/
customCss: []
customJs: []
mainSections:
  - post
images:
  - images/site-feature-image.png
doNotLoadAnimations: false
singleDateFormat: 2/1/2006
indexDateFormat: 2/1/2006
listDateFormat: 2/1/2006
reversepagetitle: true
simpleAnalytics: {}
plausibleAnalytics: {}
umami: {}
math:
  enable: false
  use: katex
socialIcons:
  - icon: fab fa-github
    title: GitHub
    url: 'https://github.com/afrid18'
  - icon: fab fa-linkedin
    title: Linkedin
    url: 'https://linkedin.com/in/afridhussain'
  - icon: fas fa-envelope
    title: E-mail
    url: 'mailto:afridhussain.d@gmail.com'
  - icon: fab fa-twitter
    title: Twitter
    url: 'https://twitter.com/afrid1808'
mermaid:
  copyright: '2020-{{ YEAR }}'

