baseURL = 'https://afridhussain.tech'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'anatole'

# Basic parameters
[params]
title = "I'm Afrid Hussain"
author = "Afrid Hussain"
# description = "Open source enthusiast"
profilePicture = "images/solana.jpeg"
description = """
Open Source enthusiast
Currently Blogging about GSoC'23
"""
favicon = "favicons/"


# Social Icons
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/afrid18"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/afridhussain"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "E-mail"
url = "mailto:afridhussain.d@gmail.com"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/afrid1808"

